### ISSUE TITLE
createLabels is not defined

### ISSUE THREAD

**Issue by MoOx** [popomore/github-labels#10]
```console
$ github-labels stylelint/stylelint
>> Authorized
>> Create labels
/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:292
    throw err;
          ^
ReferenceError: createLabels is not defined
    at Object.createLabels [as create] (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/lib/label.js:71:6)
    at callee$1$0$ (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/index.js:58:22)
    at tryCatch (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:234:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:270:19)
    at next (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:74:21)
    at /Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:93:18
    at Immediate._onImmediate (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:52:14)
```

**Comment by MoOx** [comment]
Closed by 76a93d9183d35dce79880b932000fb9bca594eca
