### ISSUE TITLE
deleteAll not defined

### ISSUE THREAD

**Issue by MoOx** [popomore/github-labels#9]
```console
$ github-labels stylelint/stylelint -f
>> Token error, fetching new token
>> No permission, enter your username and password:
[?] username: MoOx
[?] password: ********************
Token created!
>> Saving token
>> Authorized
>> Delete existing labels
/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:292
    throw err;
          ^
ReferenceError: deleteAll is not defined
    at Object.deleteAll (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/lib/label.js:110:6)
    at callee$1$0$ (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/index.js:50:22)
    at tryCatch (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:234:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as next] (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/gnode/node_modules/regenerator/runtime.js:270:19)
    at next (/Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:74:21)
    at /Users/MoOx/.nvm/versions/node/v0.12.2/lib/node_modules/github-labels/node_modules/co/index.js:93:18
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by popomore** [comment]
Which version do you use?

**Comment by MoOx** [comment]
I just installed it, so 0.5.0.
with node 0.12.2

**Comment by popomore** [comment]
I have release 0.5.1, I don't know why it will trigger this bug, but it has fixed in my local.

**Comment by popomore** [comment]
I recommend to use iojs that support generator without using --harmony flag :smile:

**Comment by MoOx** [comment]
Yeah I will do that :)
I was just waiting to see if node and iojs will merge someday, but I guess it's is not likely to happen.

**Comment by MoOx** [comment]
Ok you totally fixed this for node. Thanks !
